logLevel: info
logTimeFormat: rfc3339
healthCheckTimeout: 15
sendLoadingState: true

peers:
  opencode:
    proxy: http://127.0.0.1:6446
    models:
      - ocf-mimo-v2.5-free
      - ocf-deepseek-v4-flash-free
      - ocf-north-mini-code-free
      - ocf-nemotron-3-ultra-free
      - ocf-big-pickle

  deepseek:
    proxy: http://127.0.0.1:18632
    models:
      - dsf-deepseek-chat
      - dsf-deepseek-reasoner

  mimo:
    proxy: http://127.0.0.1:8788?key=sk-mimo-keeper-unique-key
    models:
      - mcf-mimo-auto
